version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.7
    commands:
      - bundle install

  pre_build:
    commands:
      - echo Preparing to deploy...

  build:
    commands:
      - echo Build completed on `date`

  post_build:
    commands:
      - echo Deployment completed on `date`

artifacts:
  files:
    - "**/*"
